-- AREX deterministic reset/seed is now managed by backend/scripts/reset_and_seed.py
--
-- Why:
-- - Includes Supabase Auth user lifecycle (create/delete) in addition to app tables.
-- - Keeps profile UUIDs synchronized with auth.users UUIDs.
-- - Seeds both master and workflow data in a single repeatable command.
--
-- Usage:
--   cd backend
--   uv run python scripts/reset_and_seed.py --confirm RESET_AREX_DATA
--
-- This file is intentionally kept as a pointer to avoid divergence between SQL-only
-- seeds and auth-aware seed requirements.
